# Generated by Django 4.2.1 on 2023-06-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slno', models.IntegerField(max_length=20)),
                ('item_name', models.CharField(max_length=300)),
                ('desc', models.TextField(max_length=500)),
            ],
        ),
    ]
